services:
  db:
    image: postgres:16-alpine
    container_name: resume-seo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: resume_db
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: resume
    ports:
      - "5452:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resume -d resume_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:


